import { Router } from 'express';
import CategoryRoute from './modules/category/category.route';
import ProductRoute from './modules/product/product.route';
import StreamRoute from './modules/stream/stream.route';
import AuthRoute from './modules/auth/auth.route';
import UserRoute from './modules/user/user.route';
import OrderRoute from './modules/order/order.route';
import RequestRoute from './modules/request/request.route';
import SettingRoute from './modules/setting/setting.route';
import PaymentRoute from './modules/payment/payment.route';
import CompetitionRoute from './modules/competition/competition.route';
import OperatorRoute from './modules/operator/operator.route';
import BlackListRoute from './modules/blacklist/blacklist.route';
import BotSettingsRoute from './modules/botSettings/botSettings.route';
import SmsServiceRoute from './modules/smsSettings/sms.route';
import ExpoRoute from './modules/expo/expo.route';
import SecurityRoute from './modules/security/security.route';
import FeaturesRoute from './modules/features/features.route';
import SubFeaturesRoute from './modules/subfeatures/subfeatures.route';
import SessionsRoute from './modules/sessions/sessions.route';
import { CommentsRoute } from './modules/comments/comments.route';
import InvoicesRoute from './modules/invoices/invoices.route';
import CardRoute from './modules/cards/cards.route';
import BannersRoute from './modules/banner/banner.route';
import BrandsRoute from './modules/brands/brands.route';

const router = Router();

const categoriesRoute = new CategoryRoute();
const productsRoute = new ProductRoute();
const streamRoute = new StreamRoute();
const authRoute = new AuthRoute();
const userRoute = new UserRoute();
const orderRoute = new OrderRoute();
const requestRoute = new RequestRoute();
const settingRoute = new SettingRoute();
const paymentRoute = new PaymentRoute();
const competitionRoute = new CompetitionRoute();
const operatorRoute = new OperatorRoute();
const blackListRoute = new BlackListRoute();
const botSettingsRoute = new BotSettingsRoute();
const smsServiceRoute = new SmsServiceRoute();
const expoRoute = new ExpoRoute();
const featuresRoute = new FeaturesRoute();
const securityRoute = new SecurityRoute();
const subFeaturesRoute = new SubFeaturesRoute();
const sessionsRoute = new SessionsRoute();
const commentsRoute = new CommentsRoute();
const invoicesRoute = new InvoicesRoute();
const cardsRoute = new CardRoute();
const bannersRoute = new BannersRoute();
const brandsRoute = new BrandsRoute();

router.use('/', categoriesRoute.router);
router.use('/', productsRoute.router);
router.use('/', streamRoute.router);
router.use('/', orderRoute.router);
router.use('/', userRoute.router);
router.use('/', authRoute.router);
router.use('/', requestRoute.router);
router.use('/', settingRoute.router);
router.use('/', paymentRoute.router);
router.use('/', competitionRoute.router);
router.use('/', operatorRoute.router);
router.use('/', blackListRoute.router);
router.use('/', botSettingsRoute.router);
router.use('/', smsServiceRoute.router);
router.use('/', expoRoute.router);
router.use('/', featuresRoute.router);
router.use('/', subFeaturesRoute.router);
router.use('/', securityRoute.router);
router.use('/', sessionsRoute.router);
router.use('/', commentsRoute.router);
router.use('/', invoicesRoute.router);
router.use('/', cardsRoute.router);
router.use('/', bannersRoute.router);
router.use('/', brandsRoute.router);

export default router;
